"""image added

Revision ID: a655ff20f45e
Revises: 46cc28daecdc
Create Date: 2025-08-31 16:46:47.926373

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a655ff20f45e"
down_revision: Union[str, Sequence[str], None] = "46cc28daecdc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "images_metadata",
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("upload_date", sa.DateTime(), nullable=False),
        sa.Column("bucket_name", sa.String(length=255), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column(
        "categories", "image", existing_type=sa.UUID(), nullable=True
    )
    op.alter_column(
        "products", "main_image", existing_type=sa.UUID(), nullable=True
    )
    op.alter_column(
        "products",
        "gallery",
        existing_type=postgresql.ARRAY(sa.UUID()),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "products",
        "gallery",
        existing_type=postgresql.ARRAY(sa.UUID()),
        nullable=False,
    )
    op.alter_column(
        "products", "main_image", existing_type=sa.UUID(), nullable=False
    )
    op.alter_column(
        "categories", "image", existing_type=sa.UUID(), nullable=False
    )
    op.drop_table("images_metadata")
    # ### end Alembic commands ###
