"""Add created_at and updated_at to Category

Revision ID: 8a3018c9b481
Revises: a655ff20f45e
Create Date: 2025-08-31 17:25:39.674767

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8a3018c9b481"
down_revision: Union[str, Sequence[str], None] = "a655ff20f45e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "categories", sa.Column("created_at", sa.DateTime(), nullable=False)
    )
    op.add_column(
        "categories", sa.Column("updated_at", sa.DateTime(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("categories", "updated_at")
    op.drop_column("categories", "created_at")
    # ### end Alembic commands ###
